name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  validate-composer:
    name: Composer & Code Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Lint PHP files
        run: find src -name '*.php' -print0 | xargs -0 -n1 php -l